### ISSUE TITLE
readQR error

### ISSUE THREAD

**Issue by drag0n-app** [paulmillr/qr#5]
Node.js v18.16.0

```js
import writeQR from '@paulmillr/qr';
const gifBytes = writeQR('Hello world', 'gif');

import readQR from '@paulmillr/qr/decode.js';
const decoded = readQR({ height: 120, width: 120, data: gifBytes });

Uncaught Error Error: Finder: len(found) = 0
    at findFinder (/Users/xxx/Desktop/test/node_modules/.pnpm/@paulmillr+qr@0.1.1/node_modules/@paulmillr/qr/decode.js:362:15)
    at detect (/Users/xxx/Desktop/test/node_modules/.pnpm/@paulmillr+qr@0.1.1/node_modules/@paulmillr/qr/decode.js:539:28)
    at readQR (/Users/xxx/Desktop/test/node_modules/.pnpm/@paulmillr+qr@0.1.1/node_modules/@paulmillr/qr/decode.js:863:30)
    at <anonymous> (/Users/xxx/Desktop/test/index.js:5:17)
    at run (internal/modules/esm/module_job:194:25)
    --- await ---
    at processTicksAndRejections (internal/process/task_queues:95:5)
    --- await ---
    at runMainESM (internal/modules/run_main:55:21)
    at executeUserEntryPoint (internal/modules/run_main:78:5)
    at <anonymous> (internal/main/run_main_module:23:47)
```

**Comment by paulmillr** [comment]
```
// We don't have gif reader!
import writeQR from '@paulmillr/qr';
import readQR from '@paulmillr/qr/decode.js';
import { Bitmap } from '@paulmillr/qr';
import gif from 'omggif';

function parseGIF(image) {
  const r = new gif.GifReader(image);
  const data = [];
  r.decodeAndBlitFrameRGBA(0, data);
  const { width, height } = r.frameInfo(0);
  return { width, height, data };
}

// Scale so it would be 100x100 instead of 25x25
const opts = { scale: 4 };

// Use raw bitmap
{
  const bmBits = writeQR('Hello world', 'raw', opts);
  const bm = new Bitmap({ width: bmBits[0].length, height: bmBits.length });
  bm.data = bmBits;
  const decoded = readQR(bm.toImage());
  console.log('decoded(pixels)', decoded);
}
// Or use external GIF decoder
{
  const gifBytes = writeQR('Hello world', 'gif', opts);
  const decoded = readQR(parseGIF(gifBytes));
  console.log('decoded(gif)', decoded);
}
// Other options: draw gif/svg to canvas && read back

/*
Output:
decoded(pixels) Hello world
decoded(gif) Hello world

package.json:
{
  "type":"module",
  "dependencies": {
    "@paulmillr/qr": "^0.1.1",
    "omggif": "^1.0.10"
  }
}
*/
```

**Comment by kikohs** [comment]
I'm trying to decode from a base64 PNG and have the same error.
The png was created by rasterizing the SVG. It works with my phone, the imageData has some 0 and 255 values

`const bmp = toBitmap(img, opts.isRGB);` in decode.js returns only a matrix of `true`.

Thank you

**Comment by kikohs** [comment]
I found the error, the SVG returns doesn't include a white background which makes it impossible to read back.

Could be handy to add this as well. 
thank you
```
function svgToPng(svgData, width, height) {
    return new Promise((resolve, reject) => {
        const domparser = new DOMParser();
        const doc = domparser.parseFromString(svgData, 'image/svg+xml');

        const svgElement = doc.documentElement;
        const rect = doc.createElementNS('http://www.w3.org/2000/svg', 'rect');

        rect.setAttribute('width', '100%');
        rect.setAttribute('height', '100%');
        rect.setAttribute('fill', 'white');
        svgElement.insertBefore(rect, svgElement.firstChild);

        const serializer = new XMLSerializer();
        const source = serializer.serializeToString(doc);

        const img = new Image();
        img.src = "data:image/svg+xml," + encodeURIComponent(source);
        img.onload = function() {
            const canvas = document.createElement('canvas');
            canvas.width = width;
            canvas.height = height;
            const ctx = canvas.getContext('2d');
            ctx.drawImage(img, 0, 0, width, height);
            const dataUrl = canvas.toDataURL('image/png');
            resolve(dataUrl);
        };
        img.onerror = reject;
    });
}
```

**Comment by paulmillr** [comment]
We can't add it anywhere because it uses DOM stuff, and we don't depend on dom.
